version: "3.7"
services:
  database_master:
    image: bitnami/postgresql:14.1.0
    restart: always
    env_file:
      - .env
    volumes:
      - './postgresql_master_data:/bitnami/postgresql'
      - './script.sql:/docker-entrypoint-initdb.d/script.sql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE=$POSTGRESQL_DATABASE
      - POSTGRESQL_REPLICATION_USER=$POSTGRESQL_REPLICATION_USER
      - POSTGRESQL_REPLICATION_PASSWORD=$POSTGRESQL_REPLICATION_PASSWORD
    ports:
      - 5432
  database_slave:
    image: bitnami/postgresql:14.1.0
    restart: always
    depends_on:
      - database_master
    env_file:
      - .env
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave 
      - POSTGRESQL_REPLICATION_USER=$POSTGRESQL_REPLICATION_USER
      - POSTGRESQL_REPLICATION_PASSWORD=$POSTGRESQL_REPLICATION_PASSWORD
      - POSTGRESQL_MASTER_HOST=database_master
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    deploy:
      replicas: $DB_REPLICAS
    ports:
      - 5432
  api:
    build: ./api
    restart: always
    depends_on:
      - database_master
      - database_slave
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE=$POSTGRESQL_DATABASE
      - POSTGRESQL_REPLICATION_USER=$POSTGRESQL_REPLICATION_USER
      - POSTGRESQL_REPLICATION_PASSWORD=$POSTGRESQL_REPLICATION_PASSWORD
      - POSTGRESQL_MASTER_HOST=database_master
      - POSTGRESQL_SLAVE_HOST=database_slave
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_SLAVE_PORT_NUMBER=5432
      - API_PORT=$API_PORT
    deploy:
      replicas: $API_REPLICAS
    ports:
      - $API_PORT
  load_balancer:
    image: nginx:1.20.2-alpine
    restart: always
    depends_on:
      - database_master
      - database_slave
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - $LOAD_BALANCER_PORT:80